### ISSUE TITLE
No output when LintDetectorStats regex is incorrect

### ISSUE THREAD

**Issue by drewhannay** [google/android-lint-performance-probe#2]
I tried adding to the list of regular expressions in `LintDetectorStats` to include my custom lint checks when analyzing my project, but I accidentally had a typo in my regular expression.

I had
`com.example.lint.checks..*Detector:*(*)`
instead of
`com.example.lint.checks.*Detector:*(*)`

When I ran the tool using the version with the extra `.`, it ran lint successfully but then gave no output after lint completed. I'd expect to see an error message or some kind of output rather than just nothing.

**Comment by gharrma** [comment]
Unfortunately this is due to the way the YourKit agent handles probe annotations. Basically, if it finds anything wrong with the annotations or their values, it will silently(!) ignore the probe entirely.

One way to tell that something went wrong is to run `java` with the generated JVM args. YourKit should print a line to stderr like
```
[YourKit Java Profiler 2018.04-b88] Log file: /usr/local/google/home/gharrma/.yjp/log/java-175037.log
```
In the case of this particular regex typo that file will contain a line like
```
18.04-88 0.056: Error: probe class com.android.tools.probes.LintDetectorStats$WrapDetectors: class name pattern is invalid: com.example.lint.checks..*Detector
```

Ideally there would be a [YourKit startup option](https://www.yourkit.com/docs/java/help/startup_options.jsp) to more loudly declare the error. I don't see one, though, so for now I'll probably update the README to at least warn about this scenario. Thank you for creating this issue!
